Adjust gh workflows

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -122,15 +122,15 @@ jobs:
           chmod 0600 ./config ./config_legacy ./config_v097_compatible_with_service_user
 
       - name: Run unit tests
-        # pipefail needs to be set to ensure that the exit code of make test command is captured even when piped (otherwise it would take the exit code of make upload-test-results)
+        # pipefail needs to be set to ensure that the exit code of make test command is captured even when piped (otherwise it would take the exit code of make save-test-results)
         run: set -o pipefail && make test-unit | make save-test-results
         if: ${{ !cancelled() && steps.create_config.conclusion == 'success' }}
         env:
           TEST_SF_TF_TEST_TYPE: "unit"
 
       - name: Run integration tests
-        # pipefail needs to be set to ensure that the exit code of make test command is captured even when piped (otherwise it would take the exit code of make upload-test-results)
-        run: set -o pipefail && make test-integration | make upload-test-results
+        # pipefail needs to be set to ensure that the exit code of make test command is captured even when piped (otherwise it would take the exit code of make save-test-results)
+        run: set -o pipefail && make test-integration | make save-test-results
         if: ${{ !cancelled() && steps.create_config.conclusion == 'success' }}
         env:
           TEST_SF_TF_TEST_TYPE: "integration"
@@ -153,14 +153,14 @@ jobs:
           terraform_wrapper: false
 
       - name: Run functional tests of the underlying terraform libraries
-        # pipefail needs to be set to ensure that the exit code of make test command is captured even when piped (otherwise it would take the exit code of make upload-test-results)
-        run: set -o pipefail && make test-functional | make upload-test-results
+        # pipefail needs to be set to ensure that the exit code of make test command is captured even when piped (otherwise it would take the exit code of make save-test-results)
+        run: set -o pipefail && make test-functional | make save-test-results
         if: ${{ !cancelled() && steps.setup_terraform.conclusion == 'success' }}
 
 
       - name: Run acceptance tests
-        # pipefail needs to be set to ensure that the exit code of make test command is captured even when piped (otherwise it would take the exit code of make upload-test-results)
-        run: set -o pipefail && make test-acceptance | make upload-test-results
+        # pipefail needs to be set to ensure that the exit code of make test command is captured even when piped (otherwise it would take the exit code of make save-test-results)
+        run: set -o pipefail && make test-acceptance | make save-test-results
         if: ${{ !cancelled() && steps.setup_terraform.conclusion == 'success' }}
         env:
           TEST_SF_TF_TEST_TYPE: "acceptance"
