Add workflow ID for test results and enhance test commands

diff --git a/.github/workflows/tests-account-level.yml b/.github/workflows/tests-account-level.yml
--- a/.github/workflows/tests-account-level.yml
+++ b/.github/workflows/tests-account-level.yml
@@ -23,6 +23,7 @@ jobs:
     env:
       ## adding additional suffix to don't have conflict in non-account level tests and their pre-created objects
       TEST_SF_TF_TEST_OBJECT_SUFFIX: ${{ format('{0}{1}', ((github.event_name == 'repository_dispatch' && github.event.client_payload.pull_request.head.sha) || (github.event_name == 'pull_request' && github.event.pull_request.head.sha)), 'AL') }}
+      TEST_SF_TF_TEST_WORKFLOW_ID: "${{ (github.event_name == 'repository_dispatch' && github.event.client_payload.pull_request.head.sha) || (github.event_name == 'pull_request' && github.event.pull_request.head.sha) }}_${{ github.run_attempt }}"
     name: Run all account-level tests
     runs-on: ubuntu-latest
     if: (github.event_name == 'repository_dispatch') || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
@@ -128,11 +129,12 @@ jobs:
           terraform_wrapper: false
 
       - name: Run integration and acceptance account-level tests
-        run: make test-account-level-features | make upload-test-results
+        run: |
+          set -o pipefail # called to ensure that the exit code of make test command is captured even when piped (otherwise it would take the exit code of make upload-test-results)
+          make make test-account-level-features | make upload-test-results
         if: ${{ !cancelled() && steps.setup_terraform.conclusion == 'success' }}
         env:
           TEST_SF_TF_TEST_TYPE: "account_level"
-          TEST_SF_TF_TEST_WORKFLOW_ID: "${{ (github.event_name == 'repository_dispatch' && github.event.client_payload.pull_request.head.sha) || (github.event_name == 'pull_request' && github.event.pull_request.head.sha) }}_${{ github.run_attempt }}"
           SNOWFLAKE_BUSINESS_CRITICAL_ACCOUNT: ${{ secrets.SNOWFLAKE_BUSINESS_CRITICAL_ACCOUNT }}
           TEST_SF_TF_AWS_EXTERNAL_BUCKET_URL: ${{ secrets.TEST_SF_TF_AWS_EXTERNAL_BUCKET_URL }}
           TEST_SF_TF_AWS_EXTERNAL_KEY_ID: ${{ secrets.TEST_SF_TF_AWS_EXTERNAL_KEY_ID }}
diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -16,6 +16,7 @@ jobs:
     environment: test
     env:
       TEST_SF_TF_TEST_OBJECT_SUFFIX: ${{ (github.event_name == 'repository_dispatch' && github.event.client_payload.pull_request.head.sha) || (github.event_name == 'pull_request' && github.event.pull_request.head.sha) }}
+      TEST_SF_TF_TEST_WORKFLOW_ID: "${{ (github.event_name == 'repository_dispatch' && github.event.client_payload.pull_request.head.sha) || (github.event_name == 'pull_request' && github.event.pull_request.head.sha) }}_${{ github.run_attempt }}"
     name: Run All
     runs-on: ubuntu-latest
     if: (github.event_name == 'repository_dispatch') || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
@@ -111,65 +112,60 @@ jobs:
 
       - name: Run unit tests
         run: |
-          set -o pipefail # called to ensure that the exit code of make test-unit is captured even when piped (otherwise it would take the exit code of make upload-test-results)
+          set -o pipefail # called to ensure that the exit code of make test command is captured even when piped (otherwise it would take the exit code of make upload-test-results)
           make test-unit | make upload-test-results
         if: ${{ !cancelled() && steps.create_config.conclusion == 'success' }}
         env:
           TEST_SF_TF_TEST_TYPE: "unit"
-          TEST_SF_TF_TEST_WORKFLOW_ID: "${{ (github.event_name == 'repository_dispatch' && github.event.client_payload.pull_request.head.sha) || (github.event_name == 'pull_request' && github.event.pull_request.head.sha) }}_${{ github.run_attempt }}"
 
-#      - name: Run functional tests of the underlying terraform libraries
-#        run: go run ./pkg/scripts/test_runner/test_runner.go
-#        if: ${{ !cancelled() && steps.create_config.conclusion == 'success' }}
-#        env:
-#          TEST_SF_TF_TEST_TYPE: "functional"
-#          TEST_SF_TF_TEST_WORKFLOW_ID: "${{ (github.event_name == 'repository_dispatch' && github.event.client_payload.pull_request.head.sha) || (github.event_name == 'pull_request' && github.event.pull_request.head.sha) }}_${{ github.run_attempt }}"
-#
-#      - name: Run integration tests
-#        run: go run ./pkg/scripts/test_runner/test_runner.go
-#        if: ${{ !cancelled() && steps.create_config.conclusion == 'success' }}
-#        env:
-#          TEST_SF_TF_TEST_TYPE: "integration"
-#          TEST_SF_TF_TEST_WORKFLOW_ID: "${{ (github.event_name == 'repository_dispatch' && github.event.client_payload.pull_request.head.sha) || (github.event_name == 'pull_request' && github.event.pull_request.head.sha) }}_${{ github.run_attempt }}"
-#          SNOWFLAKE_BUSINESS_CRITICAL_ACCOUNT: ${{ secrets.SNOWFLAKE_BUSINESS_CRITICAL_ACCOUNT }}
-#          TEST_SF_TF_AWS_EXTERNAL_BUCKET_URL: ${{ secrets.TEST_SF_TF_AWS_EXTERNAL_BUCKET_URL }}
-#          TEST_SF_TF_AWS_EXTERNAL_KEY_ID: ${{ secrets.TEST_SF_TF_AWS_EXTERNAL_KEY_ID }}
-#          TEST_SF_TF_AWS_EXTERNAL_ROLE_ARN: ${{ secrets.TEST_SF_TF_AWS_EXTERNAL_ROLE_ARN }}
-#          TEST_SF_TF_AWS_EXTERNAL_SECRET_KEY: ${{ secrets.TEST_SF_TF_AWS_EXTERNAL_SECRET_KEY }}
-#          TEST_SF_TF_AZURE_EXTERNAL_BUCKET_URL: ${{ secrets.TEST_SF_TF_AZURE_EXTERNAL_BUCKET_URL }}
-#          TEST_SF_TF_AZURE_EXTERNAL_SAS_TOKEN: ${{ secrets.TEST_SF_TF_AZURE_EXTERNAL_SAS_TOKEN }}
-#          TEST_SF_TF_AZURE_EXTERNAL_TENANT_ID: ${{ secrets.TEST_SF_TF_AZURE_EXTERNAL_TENANT_ID }}
-#          TEST_SF_TF_GCS_EXTERNAL_BUCKET_URL: ${{ secrets.TEST_SF_TF_GCS_EXTERNAL_BUCKET_URL }}
+      - name: Run integration tests
+        run: |
+          set -o pipefail # called to ensure that the exit code of make test command is captured even when piped (otherwise it would take the exit code of make upload-test-results)
+          make test-integration | make upload-test-results
+        if: ${{ !cancelled() && steps.create_config.conclusion == 'success' }}
+        env:
+          TEST_SF_TF_TEST_TYPE: "integration"
+          SNOWFLAKE_BUSINESS_CRITICAL_ACCOUNT: ${{ secrets.SNOWFLAKE_BUSINESS_CRITICAL_ACCOUNT }}
+          TEST_SF_TF_AWS_EXTERNAL_BUCKET_URL: ${{ secrets.TEST_SF_TF_AWS_EXTERNAL_BUCKET_URL }}
+          TEST_SF_TF_AWS_EXTERNAL_KEY_ID: ${{ secrets.TEST_SF_TF_AWS_EXTERNAL_KEY_ID }}
+          TEST_SF_TF_AWS_EXTERNAL_ROLE_ARN: ${{ secrets.TEST_SF_TF_AWS_EXTERNAL_ROLE_ARN }}
+          TEST_SF_TF_AWS_EXTERNAL_SECRET_KEY: ${{ secrets.TEST_SF_TF_AWS_EXTERNAL_SECRET_KEY }}
+          TEST_SF_TF_AZURE_EXTERNAL_BUCKET_URL: ${{ secrets.TEST_SF_TF_AZURE_EXTERNAL_BUCKET_URL }}
+          TEST_SF_TF_AZURE_EXTERNAL_SAS_TOKEN: ${{ secrets.TEST_SF_TF_AZURE_EXTERNAL_SAS_TOKEN }}
+          TEST_SF_TF_AZURE_EXTERNAL_TENANT_ID: ${{ secrets.TEST_SF_TF_AZURE_EXTERNAL_TENANT_ID }}
+          TEST_SF_TF_GCS_EXTERNAL_BUCKET_URL: ${{ secrets.TEST_SF_TF_GCS_EXTERNAL_BUCKET_URL }}
 
-#      - name: Setup Terraform
-#        if: ${{ !cancelled() && steps.create_config.conclusion == 'success' }}
-#        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
-#        id: setup_terraform
-#        with:
-#          terraform_version: 1.7.4
-#          terraform_wrapper: false
-#
-#      - name: Run functional tests of the underlying terraform libraries
-#        run: go run ./pkg/scripts/test_runner/test_runner.go
-#        if: ${{ !cancelled() && steps.setup_terraform.conclusion == 'success' }}
-#        env:
-#          TEST_SF_TF_TEST_TYPE: "acceptance"
-#          TEST_SF_TF_TEST_WORKFLOW_ID: "${{ (github.event_name == 'repository_dispatch' && github.event.client_payload.pull_request.head.sha) || (github.event_name == 'pull_request' && github.event.pull_request.head.sha) }}_${{ github.run_attempt }}"
-#          SNOWFLAKE_BUSINESS_CRITICAL_ACCOUNT: ${{ secrets.SNOWFLAKE_BUSINESS_CRITICAL_ACCOUNT }}
-#          TEST_SF_TF_AWS_EXTERNAL_BUCKET_URL: ${{ secrets.TEST_SF_TF_AWS_EXTERNAL_BUCKET_URL }}
-#          TEST_SF_TF_AWS_EXTERNAL_KEY_ID: ${{ secrets.TEST_SF_TF_AWS_EXTERNAL_KEY_ID }}
-#          TEST_SF_TF_AWS_EXTERNAL_ROLE_ARN: ${{ secrets.TEST_SF_TF_AWS_EXTERNAL_ROLE_ARN }}
-#          TEST_SF_TF_AWS_EXTERNAL_SECRET_KEY: ${{ secrets.TEST_SF_TF_AWS_EXTERNAL_SECRET_KEY }}
-#          TEST_SF_TF_AZURE_EXTERNAL_BUCKET_URL: ${{ secrets.TEST_SF_TF_AZURE_EXTERNAL_BUCKET_URL }}
-#          TEST_SF_TF_AZURE_EXTERNAL_SAS_TOKEN: ${{ secrets.TEST_SF_TF_AZURE_EXTERNAL_SAS_TOKEN }}
-#          TEST_SF_TF_AZURE_EXTERNAL_TENANT_ID: ${{ secrets.TEST_SF_TF_AZURE_EXTERNAL_TENANT_ID }}
-#          TEST_SF_TF_GCS_EXTERNAL_BUCKET_URL: ${{ secrets.TEST_SF_TF_GCS_EXTERNAL_BUCKET_URL }}
-#
-#      - name: Save test results
-#        run: go run ./pkg/scripts/save_test_results/save_test_results.go
-#        env:
-#          TEST_SF_TF_TEST_TYPES_IN_WORKFLOW: "unit,integration,acceptance,functional"
-#          TEST_SF_TF_TEST_WORKFLOW_ID: "${{ (github.event_name == 'repository_dispatch' && github.event.client_payload.pull_request.head.sha) || (github.event_name == 'pull_request' && github.event.pull_request.head.sha) }}_${{ github.run_attempt }}"
+      - name: Setup Terraform
+        if: ${{ !cancelled() && steps.create_config.conclusion == 'success' }}
+        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
+        id: setup_terraform
+        with:
+          terraform_version: 1.7.4
+          terraform_wrapper: false
+
+      - name: Run functional tests of the underlying terraform libraries
+        run: |
+          set -o pipefail # called to ensure that the exit code of make test command is captured even when piped (otherwise it would take the exit code of make upload-test-results)
+          make test-functional | make upload-test-results
+        if: ${{ !cancelled() && steps.setup_terraform.conclusion == 'success' }}
+
+
+      - name: Run acceptance tests
+        run: |
+          set -o pipefail # called to ensure that the exit code of make test command is captured even when piped (otherwise it would take the exit code of make upload-test-results)
+          make test-acceptance | make upload-test-results
+        if: ${{ !cancelled() && steps.setup_terraform.conclusion == 'success' }}
+        env:
+          TEST_SF_TF_TEST_TYPE: "functional"
+          SNOWFLAKE_BUSINESS_CRITICAL_ACCOUNT: ${{ secrets.SNOWFLAKE_BUSINESS_CRITICAL_ACCOUNT }}
+          TEST_SF_TF_AWS_EXTERNAL_BUCKET_URL: ${{ secrets.TEST_SF_TF_AWS_EXTERNAL_BUCKET_URL }}
+          TEST_SF_TF_AWS_EXTERNAL_KEY_ID: ${{ secrets.TEST_SF_TF_AWS_EXTERNAL_KEY_ID }}
+          TEST_SF_TF_AWS_EXTERNAL_ROLE_ARN: ${{ secrets.TEST_SF_TF_AWS_EXTERNAL_ROLE_ARN }}
+          TEST_SF_TF_AWS_EXTERNAL_SECRET_KEY: ${{ secrets.TEST_SF_TF_AWS_EXTERNAL_SECRET_KEY }}
+          TEST_SF_TF_AZURE_EXTERNAL_BUCKET_URL: ${{ secrets.TEST_SF_TF_AZURE_EXTERNAL_BUCKET_URL }}
+          TEST_SF_TF_AZURE_EXTERNAL_SAS_TOKEN: ${{ secrets.TEST_SF_TF_AZURE_EXTERNAL_SAS_TOKEN }}
+          TEST_SF_TF_AZURE_EXTERNAL_TENANT_ID: ${{ secrets.TEST_SF_TF_AZURE_EXTERNAL_TENANT_ID }}
+          TEST_SF_TF_GCS_EXTERNAL_BUCKET_URL: ${{ secrets.TEST_SF_TF_GCS_EXTERNAL_BUCKET_URL }}
 
       - name: Sweepers cleanup
         if: ${{ always() && steps.setup_go.conclusion == 'success' }}
